# build.yaml

targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assetsPath: 'lib/graphqlSection/**.graphql'
          clients:
            - graphql
            - graphql_flutter
